name: Deploy to Production Environment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # 承認が必要な環境を指定
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-backend:prod
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-frontend:prod
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simple-memo-app-backend-prod'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-backend:prod'
          app-settings: |
            WEBSITES_PORT=80
            ENVIRONMENT=production
      
      - name: Deploy to Azure Web App (Frontend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simple-memo-app-frontend-prod'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-frontend:prod'
          app-settings: |
            NEXT_PUBLIC_API_URL=https://simple-memo-app-backend-prod.azurewebsites.net