name: Rollback (Manual Trigger)

# 手動トリガーで実行できるようにする
on:
  workflow_dispatch:
    inputs:
      backend_tag:
        description: 'ロールバックするバックエンドイメージのタグ'
        required: true
        type: string
      frontend_tag:
        description: 'ロールバックするフロントエンドイメージのタグ'
        required: true
        type: string
      environment:
        description: 'ロールバック対象の環境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - development

jobs:
  rollback:
    runs-on: ubuntu-latest
    # 本番環境へのロールバックの場合は承認が必要
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # バックエンドのロールバック
      - name: Rollback Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simple-memo-app-backend-${{ github.event.inputs.environment == "production" && "prod" || "dev" }}'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-backend:${{ github.event.inputs.backend_tag }}'
      
      # フロントエンドのロールバック
      - name: Rollback Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'simple-memo-app-frontend-${{ github.event.inputs.environment == "production" && "prod" || "dev" }}'
          images: '${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-frontend:${{ github.event.inputs.frontend_tag }}'
      
      # ロールバック完了通知
      - name: Rollback Notification
        run: |
          echo "ロールバックが完了しました。"
          echo "環境: ${{ github.event.inputs.environment }}"
          echo "バックエンドイメージ: ${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-backend:${{ github.event.inputs.backend_tag }}"
          echo "フロントエンドイメージ: ${{ secrets.ACR_LOGIN_SERVER }}/simple-memo-app-frontend:${{ github.event.inputs.frontend_tag }}"